### ISSUE TITLE
Useable version

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#1]
Theres any to exists? 
I would really like to get a codeigniter based blog since I have some experience with it, (far better structure than wordpress).

Any of the versions on the site are working?

**Comment by enlivenapp** [comment]
I'm currently writing version 3.  It's still a work in progress.  I don't have an ETA on a completed, production-ready release yet.  

You *could* use v1.x....  but it's written on CI 1.7.2 and is a complete mess. I can't even get it to run properly on PHP 5.6.

**Comment by Frontrider** [comment]
Yeah, I tried them. They don't work in any way. I did got to encounter the issues of old codeigniter.

**Comment by enlivenapp** [comment]
If you find any issues once it's in beta, feel free to let me know.
