### ISSUE TITLE
Translate French

### ISSUE THREAD

**Issue by enlivenapp** [enlivenapp/Open-Blog-3#10]
Includes all folders in application/language/[language]

**Comment by keeganpa** [comment]
i'm working on it with 2 guys.

**Comment by intv0id** [comment]
Working on it w/ keeganpa

**Comment by Ignamarte** [comment]
Hi, I just subbmited à PR for the translation. I just need some clarification : what does ATOM comment refers to ?

**Comment by enlivenapp** [comment]
@Ignamarte I should have removed that.  No need to translate RSS and ATOM, they are depreciated and won't be used.     To answer your question, it's similar to RSS, just another protocol.


@Ignamarte, @intv0id, @keeganpa,  Thanks so much for the translations.  Don't forget to add a README.md update with names/links for each of you under translations!

**Comment by intv0id** [comment]
I just modified the README.md. Thanks a lot.

**Comment by enlivenapp** [comment]
So, in figuring out how to merge multiple PRs, I've seem to have run into an issue.

Is it possible you guys can merge the multiple admin_lang.php all together and submit a single PR with all changes for that file? 

The issue is in admin_lang because there's changes over multiple PRs where some is still in english and some in french, then when the next PR is merged, english will overwrite the french and french over the english....

If that's too difficult, I'll just pull copies of the PRs and make a single commit with all changes in admin_lang.php.

**Comment by Ignamarte** [comment]
Of course ! 
It should be ok if you first merge intv0id and keeganpa (since they changed other files alone), deny mine and then merge leoDisjonct's PR with the complet file translated. (He's going to send it asap)

**Comment by ghost** [comment]
+1 Ignamarte, I just sent my PR

**Comment by enlivenapp** [comment]
If I read it all correctly, it looks like there were conflicting changes to #34 in auth_lang that were meant for admin_lang?

**Comment by enlivenapp** [comment]
Many thanks to you gentlemen!
