### ISSUE TITLE
Translate Hungarian

### ISSUE THREAD

**Issue by enlivenapp** [enlivenapp/Open-Blog-3#11]
Includes all folders in application/language/[language]

**Comment by Frontrider** [comment]
I'll look into it as soon as possible.

**Comment by enlivenapp** [comment]
excellent.  Thank you.

**Comment by Frontrider** [comment]
Finally got around starting the first iteration, I'll do at least 2, so I can probably eliminate missing text and make the wording as reasonable as possible.

You have tags showing up multiple times (namely, open in blank and same window shows up at least twice, on the exact same array index). I'm gonna trim it out.
