### ISSUE TITLE
Translate Indonesian

### ISSUE THREAD

**Issue by enlivenapp** [enlivenapp/Open-Blog-3#12]
Includes all folders in application/language/[language]

**Comment by suhindra** [comment]
Hi, I am a Indonesian(Id) user of CodeIgniter and interested in translation of open blog into Indonesian languague

**Comment by enlivenapp** [comment]
Excellent.  Thank you.

I missed two things in the blog_lang.php file.  they've been added in this commit. b9432db89c80760444c58168a8bb77e1cd079dbd

**Comment by enlivenapp** [comment]
Are you still planning to do this translation?

**Comment by suhindra** [comment]
Yes, i'm sorry i was busy with work, i will do it this weekend :)

**Comment by enlivenapp** [comment]
No worries, was just checking in.   :)
