### ISSUE TITLE
Translate Portuguese

### ISSUE THREAD

**Issue by enlivenapp** [enlivenapp/Open-Blog-3#17]
Includes all folders in application/language/[language]

**Comment by fontebasso** [comment]
I started a fork to help with Portuguese translations.

https://github.com/fontebasso/Open-Blog-3

As you did not specify exactly which Portuguese (Portugal, Brazil, other), would i like to know if my contribution will be useful with the translation into Brazilian Portuguese (pt-BR)?

**Comment by fontebasso** [comment]
i'm working on it

**Comment by fontebasso** [comment]
Complete on #57
