### ISSUE TITLE
Unable to locate model:Ion_auth_model

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#2]
originally ion_auth_model whitch can have issues on its own.

It just can't seem to load the liblary from the other module.

I would suggest having interface methonds on the auth module, and don't ever call anything only through that.
have as mutch isolation as possible. I don't think you're supposed to do that anyways.

**Comment by enlivenapp** [comment]
If you're trying to install/use OB3, I'd suggest holding off.  It's in Alpha right now and I'm moving stuff all over the place.  The newest commit should allow you to play with it a bit more.
