### ISSUE TITLE
Translate Turkish

### ISSUE THREAD

**Issue by enlivenapp** [enlivenapp/Open-Blog-3#23]
Includes all folders in application/language/[language]

**Comment by ahmethakanbesel** [comment]
I checked translation and Turkish translation is OK.

**Comment by enlivenapp** [comment]
It's in English currently. 

Take a look in application/languages/Turkish

The system/language/Turkish is from the CI Dev team.

**Comment by ghost** [comment]
Update of the turkish translation.
https://github.com/You85/Open-Blog-3
