### ISSUE TITLE
[suggestion] Bring back hmvc

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#25]
Its mostly just a "think ahead" kind of thing, I would need to tinker with the authentication. I'm going to have at least 2 projects where I need to integrate a blog with phpbb. The best option would be to just replace the auth module with a new one directly using the authentication from phpbb. (in one case, I have an existing phpbb forum inside a wp site, and we can not do anything with it. Nothing can be updated.)

It should also be easy to create plugins with that. To alter content with filters, its ahrder, but if the plugin is like a webshop or something then its really good.

I hope I was clear enough, if not ask.

**Comment by enlivenapp** [comment]
It's MIT licensed, so you're welcome to do whatever you like with it.  I did remove HMVC for several reasons.

Just to clarify, Open Blog is **not** a CMS so major integrations with other software will have to be done by a developer.
