### ISSUE TITLE
[question] templating is close to being done?

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#26]
Just as a question, I would like to not to have my pains with wordpress (as far as being user friendly goes, its still horrible).
And actual use is the best way to advance forward with it.

**Comment by enlivenapp** [comment]
Templateing is almost done.  

While I haven't documented it yet, view can be overloaded in: 

     application/theme/theme_name/views/[controller]/[file_name]

I'm still struggling with assets (loading css/js from the layout, specifically).  Once that's done, all should be done.

**Comment by enlivenapp** [comment]
Tempting is done now.
