### ISSUE TITLE
Installation okay but links do not work

### ISSUE THREAD

**Issue by halojoy** [enlivenapp/Open-Blog-3#37]
I run PHP 7 on localhost, 127.0.0.1/openblog3
In step 3 of installation are 2 links.
One to the front and one for the admin.
But, I think, as I have chosen NOT to have mod_rewrite these links do not work.

**Comment by enlivenapp** [comment]
Good catch.  It looks like I assumed everyone would use mod_rewrite when generating the links.  Although, the "Click to see your website" should work.   Any errors, blank screen or just the 404?

    <a href="<?= $this->session->base_url . '/admin/' ?>">

I'll push out a fix today.
