### ISSUE TITLE
Error after the installation, Class CI_Controller not found

### ISSUE THREAD

**Issue by halojoy** [enlivenapp/Open-Blog-3#38]
I run PHP 7.

An uncaught Exception was encountered
Type: Error
Message: Class 'CI_Controller' not found
Filename: ....\openblog3\system\core\CodeIgniter.php
Line Number: 369

Backtrace:

File: ....\openblog3\application\core\OB_Lang.php
Line: 154
Function: get_instance

File: ....\openblog3\application\config\routes.php
Line: 74
Function: get

File: ....\openblog3\index.php
Line: 340
Function: require_once

**Comment by enlivenapp** [comment]
Interesting... that's coming from the config/routes.php file where it's dynamically setting `$route['default_controller']`

I've tested on MAMP and LAMP (5.6, 7, and 7.1) and haven't had an issue with it.

What's your server environment?

**Comment by dineshsg** [comment]
PHP version : 7.0.18-0ubuntu0.16.04.1
Ubuntu Operating System : 16.04
I am getting same error as of above.

An uncaught Exception was encountered
Type: Error
Message: Class 'CI_Controller' not found
Filename: /var/www/html/Oblog/system/core/CodeIgniter.php
Line Number: 369
Backtrace:
File: /var/www/html/Oblog/application/core/OB_Lang.php
Line: 154
Function: get_instance
File: /var/www/html/Oblog/application/config/routes.php
Line: 78
Function: get
File: /var/www/html/Oblog/index.php
Line: 340
Function: require_once

Please Help.

**Comment by bkader** [comment]
I had th same issue, i added this to `database.php` config file because I am using another port:

    'port => '3308',

Then I got `Message: syntax error, unexpected end of file` so I fixed the file `application\themes\default\partials\archives.php` changing this `<? endif; ?>` to `<?php endif; ?>` and everything worked.
