### ISSUE TITLE
File browser

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#42]
I finally managed to integrate a proper [file browser](http://www.roxyfileman.com/) with codeigniter,I've never pushed anything into projects like this, would you be interested in the function?

Its kinda rough around the edges, but it works.(better than the current functionality)
And, it should not be hard to port it to ci4 later on.

**Comment by enlivenapp** [comment]
Go ahead and push, I'll take a look and we can discuss it.  

Sorry for late responses, I've been out of town and crazy busy with work.
