### ISSUE TITLE
language problems

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#43]
After setting the language to the one I'm translating, its still english. In the settings menu, I see the new one selected, but the translated fields show no difference.

Edit: choosing language is not straightforward. It does not produces the expected behaviour, whitch is to change language when the default is modified in the settings. I need to change it manually afterwords.

**Comment by enlivenapp** [comment]
Yeah, I've noticed that but haven't had a chance to push up a fix.  I already know what to do, just getting time to write, test and push.
