### ISSUE TITLE
Character errors

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#44]
The blog turns"á"-s into "Ã¡". You do something with the character encoding, what you should not. (At least I guess)

**Comment by enlivenapp** [comment]
I'm a native English speaker/writer.  Sadly I don't have experience with other languages.  

I suspect it's an issue with the database encoding used or character set used when the page loads.

If you, or anyone else, can give some direction on this, I'm happy to fix it.

**Comment by enlivenapp** [comment]
This might be something @fontebasso will have some insight on?

**Comment by enlivenapp** [comment]
In researching this I've found there's a bunch of possible issues, many of which involve the database, your php.ini file, and other things.  On the [open blog website I'm unable to reproduce the issue](https://open-blog.org/page/test).

The short version of all this is your encoding needs to match all the way through the application, of which I don't have complete control over every circumstance.  Apache, etc/HTML/PHP/Database or there's a possibility that characters will be mis-encoded for the end user.

Here's a few things to consider:

Make sure your database is `char_set` to utf8, also make sure your collation is set to `utf8_general_ci` in your database.

Finally, Take a look through your settings/themes/etc...

```
=================================
:: PHP ini Settings::
=================================


default_charset = "utf-8"
mbstring.internal_encoding=utf-8
mbstring.http_output=UTF-8
mbstring.encoding_translation=On
mbstring.func_overload=6 

=================================
:: .htaccess Settings::
=================================

DefaultLanguage en-US
AddDefaultCharset UTF-8

=================================
:: HTML Header Page::
=================================

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

=================================
:: PHP Codeigniter index.php ::
=================================

header('Content-Type: text/html; charset=UTF-8');

// You don't need to do this (in CI 3.1.6 at least) as it's done for you in /system/core/Output.php

=================================
:: Codeigniter config.php ::
=================================

$config['charset'] = 'UTF-8';

=================================
:: Codeigniter database.php ::
=================================

$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';

=================================
:: Codeigniter helper function (optional)
=================================

if(!function_exists('safe_utf_string')){
    function safe_utf_string($utf8string= ''){
        $utf8string = htmlspecialchars($utf8string, ENT_QUOTES, 'UTF-8');
        return mb_convert_encoding($utf8string, 'UTF-8');
    }
}

```
From: https://stackoverflow.com/questions/1605760/how-to-best-configure-php-to-handle-a-utf-8-website
