### ISSUE TITLE
lang files missing tags

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#45]
Some tags doenst seem to work properly. 
Visible always says visible, no matter what is in the language file.

**Comment by enlivenapp** [comment]
Which tags?  I need more info to fix things like this...

**Comment by anfrajim** [comment]
Hi i had the same problem trying to install Open-Blog-3-master....... and i dont know how to fix it, i would appreciate if you can helpme.

**Comment by enlivenapp** [comment]
@anfrajim, can you give me more specific info?  I'm not sure where to look.
