### ISSUE TITLE
Page ordering does not work

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#46]
The pages are always in the sam order, whitch is their id in the database.
I see that there is no ordering field in the database anywhere.

**Comment by enlivenapp** [comment]
The pages don't need to be ordered, the navigation items are ordered so they can be shown as the site admin likes in the public menu.

**Comment by Frontrider** [comment]
Then I don't get it. Why I can drag then around, and why the tooltip tells me that I can do it like that?

**Comment by enlivenapp** [comment]
You may be confusing pages with navigation, they are separate things.

Pages, are just that, containers to hold static information for site visitors.  There's no need to reorder them.  I don't have an JS drag/drop installed for pages in the admin area.  Example: http://open-blog.org/page/about is a simple page.

Navigation items, however, are different.  They are a one to one correlation to the item (page or post) being pointed to. They can be reordered to allow positioning in the main menu site visitors see.
