### ISSUE TITLE
always fails to log in

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#5]
I can not login with the crecidentals set in the installer. admin 12345678 is pretty hard to typo/forget.
(apologies for placing it in the wrong place first)

**Comment by enlivenapp** [comment]
This is a known bug, I just haven't gotten around to fixing it yet.

It seems it's not properly salting the password you provide.

**Comment by enlivenapp** [comment]
Tested locally and now provides the correct password hash to successfully log in.

https://github.com/enlivenapp/Open-Blog-3/commit/0fc0e7ed805faa109619b0ec23756b71794a0384

Reopen/comment if not.
