### ISSUE TITLE
controller error

### ISSUE THREAD

**Issue by xaronnn** [enlivenapp/Open-Blog-3#56]
An uncaught Exception was encountered

Type: Error

Message: Class 'CI_Controller' not found

Filename: C:\wamp64\www\system\core\CodeIgniter.php

Line Number: 369

Backtrace:

File: C:\wamp64\www\application\core\OB_Lang.php
Line: 154
Function: get_instance

File: C:\wamp64\www\application\config\routes.php
Line: 78
Function: get

File: C:\wamp64\www\index.php
Line: 340
Function: require_once

**Comment by fontebasso** [comment]
Verify that the database was successfully created, 21 tables should be constructed.

I noticed that in the file that builds the tables (`installer/src/mysqli.sql`) there are some settings like the default value of a date field such as '0000-00-00 'which generates a syntax error in mysql server

Mysql Server version: 5.7.19-0ubuntu0.16.04.1

**Comment by rrfaria** [comment]
I'm having same issue 
I'm using the last wamp server version on windows https://sourceforge.net/projects/wampserver/files/WampServer%203/WampServer%203.0.0/

php 5.6.31
mysql 5.7.19
apache 2.4.27

the database is not been created right
the script just create the ob_categories table

I've changed the default date to any different date and works better install more tables but in the same time it isn't installing all tables

**Comment by fontebasso** [comment]
@rrfaria thanks for sharing!
This weekend I'll be working on the fixes in this file.

**Comment by fontebasso** [comment]
Use the file `/installer/src/mysqli.sql` of the installer-mysqli branch

Commit 38e4a81

I made the fixes for creating the tables, but I'm still checking to see if this does not affect how the system collects and inserts the data

Another alternative is to disable mysql's strict mode: https://stackoverflow.com/questions/36374335/error-in-mysql-when-setting-default-value-for-date-or-datetime
