### ISSUE TITLE
Database whitout password 

### ISSUE THREAD

**Issue by Frontrider** [enlivenapp/Open-Blog-3#6]
Can I log in whitout a password to make it easier to test? Not even wordpress requies it.

i'm talking about Installer.php lines 83,97.

**Comment by enlivenapp** [comment]
In my current installer/controllers/installer.php

Line 83: 

    if ($this->input->post('db_engine') == 'mysqli')

and like 97: 

     {


So I'm not sure what/where you're asking about.  In general, you don't need a login to run the installer, you only need create the login so you can use what the login installs.

**Comment by enlivenapp** [comment]
I think I figured out the question, you can go to auth/login/ then click Forgotten Password, then go into the phpmyadmin (or whatever) and get the code. Then go to auth/reset_password/[forgotten_password_code] and reset your password.  

Otherwise, update from master.  see #5

**Comment by Frontrider** [comment]
Right now I can't test it.
2017.01.12. 19:30 ezt írta ("Mike W" <notifications@github.com>):

**Comment by enlivenapp** [comment]
Well,  if you're not going to explain or show the errors you're getting, then I can't help or answer properly...

**Comment by Frontrider** [comment]
The error: password is requied.
The case: database password doesnt exists, because its my test environment,
and I use none. Its mostl just an annoyance, but That requiment should not
be there in the first place. If they enter no password they can not connect
anyways.

Sorry for the late responses, please bear with me, at this point I'm not in
the position to be quick.
2017.01.13. 16:56 ezt írta ("Mike W" <notifications@github.com>):

**Comment by enlivenapp** [comment]
No problem on delays.  I just need to keep the issues under control as I'm using it for more than just bugs.

On any production server you'll need a database login, password, etc...  My advice is to create one to use in your testing environment otherwise, I would adjust the form requirements in the installer to allow a blank password, or install it manually.

**Comment by Frontrider** [comment]
Removing the requirement is what I did.
Whatever, I'll just do that.
