### ISSUE TITLE
Error while creating a user

### ISSUE THREAD

**Issue by Nolasquez** [enlivenapp/Open-Blog-3#60]
While creating a new user the blog launches a error window; it cant load the "_activate.tpl.php_" file 
![captura de pantalla 17](https://user-images.githubusercontent.com/32397658/31853120-3015c070-b649-11e7-8d1e-6b52a1abb913.png)

**Comment by enlivenapp** [comment]
Ah, found the issue.    Ion_auth is calling for it from the config file.

I'll get it sorted today.  

Nice bug catch!  Thanks!
