### ISSUE TITLE
update to CodeIgniter 4

### ISSUE THREAD

**Issue by ghost** [enlivenapp/Open-Blog-3#61]
hello is an update to CodeIgniter 4 is expected in the coming days.
The version 4 of CodeIgniter will be great because it is based on php 7 which will greatly improve the speed of the site that uses it. Many other improvements are planned like the creation of a folder / public for more security ...

https://forum.codeigniter.com/thread-62615.html

**Comment by enlivenapp** [comment]
Hi there,

I do plan on creating Open Blog 4, which will be based on CI4 at some point after CI4 is officially released.  CI4 is currently still in Alpha last I looked.   I am working on the beginnings of it already but it's a long way off.  OB4 will likely be composer based and updated with composer...  maybe, that decision is not a today problem.

Thanks for all your other suggestions also, it'll take a while to work through them all.
