### ISSUE TITLE
add a theme for email

### ISSUE THREAD

**Issue by ghost** [enlivenapp/Open-Blog-3#65]
Like this : ![email template](https://user-images.githubusercontent.com/30325749/32297131-6fde5646-bf4e-11e7-84ad-d11d69c87eca.png)

**Comment by enlivenapp** [comment]
Ugh...  email themes...  

Anyone wanna give this a try?

**Comment by ghost** [comment]
Open Source Email Templates : https://www.sendwithus.com/resources/templates/meow

Link to the github project : https://github.com/sendwithus/templates
