### ISSUE TITLE
Embed Open Graph protocol

### ISSUE THREAD

**Issue by ghost** [enlivenapp/Open-Blog-3#68]
"Officially, the Opengraph has no impact on SEO, but social networks are an excellent source of traffic, and if your content is more visible on Facebook they will be much more shared, Get a much better click-through rate and therefore an increase in traffic and conversions, a relevant indicator that Google can take into account, so the impact on SEO is rather indirect."

http://ogp.me/

**Comment by enlivenapp** [comment]
OG is already incorporated 

                <meta name="title" content="Open Blog Themes" />
		<meta name="keywords" content="Open, Blog, Themes" />
		<meta name="description" content="Open Blog Themes are here!" />
		<meta property="og:title" content="Open Blog Themes" />
		<meta property="og:type" content="website" />
		<meta property="og:description" content="Open Blog Themes are here!" />
		<meta property="og:image" content="https://open-blog.org/uploads/Screen_Shot_2017-10-25_at_7_49_03_PM.png" />
		<meta property="og:url" content="https://open-blog.org/blog/open-blog-themes" />

Or do you mean something else?

**Comment by ghost** [comment]
sorry I had not seen. Thanks You
