### ISSUE TITLE
bug in the link to facebook social networks

### ISSUE THREAD

**Issue by ghost** [enlivenapp/Open-Blog-3#69]
when adding a link to the social network the script returns a 404 error.

![sans titre](https://user-images.githubusercontent.com/30325749/32329339-10400b28-bfdd-11e7-8623-323de4d91fa2.png)

**Comment by enlivenapp** [comment]
In researching this it appears you've not included `http://` or `https://` to your social link.

I've added `prep_url` to the validation rules which will add `http://` if it's not present.  `https://` is preserved if you enter it.

From the instructions: 
`Add a new social link. Just enter the Name of the social media service, the full URL (include http://) and if you want it to be active. Active links are shown on the public pages of your site.`
