### ISSUE TITLE
Suggestions for improving the comment system

### ISSUE THREAD

**Issue by ghost** [enlivenapp/Open-Blog-3#77]
Features to develop for a more sophisticated commenting system : 

- [ ] ALL AJAX
- [ ] Rating system
- [ ] Report system
- [x] Spam protection
- [ ] Comment editing
- [ ] Avatar upload
- [ ] Ajax pagination
- [ ] Admin/Modcommenting
- [x] Guest commenting
- [x] Comment approval
- [ ] User’s infocards
- [ ] Convert links to clickable links
- [ ] Emotion Systems
- [ ] Multi-level reply allowed
- [ ] Facebook Login
- [ ] Best/Newest/Oldest sorting

**Comment by enlivenapp** [comment]
Unless a very strong argument can be made for one or more of these (below) I don't see a need, they're either unnecessary or can be used maliciously.

* Avatar Uploads (for commenters)
* User's Infocards
* Convert links to clickable links
* Emotion System (emoticons)

Using facebook login just for comments adds unnecessary complication for facebook's (or anyone else's) OAuth.

Keep in mind some of this will be solely in theme. However, I can create and expose functions for AJAX/JS to access the commenting system.

I like many of these though, so some will find their way into future releases.

**Comment by ghost** [comment]
I think you're right some features can be used this way maliciously.
By the way I find a good alternative open source system to Disqus.
https://github.com/posativ/isso

What do you think ?
