### ISSUE TITLE
To disconnect a user

### ISSUE THREAD

**Issue by ghost** [enlivenapp/Open-Blog-3#78]
To disconnect a user after a period of inactivity on the site for security reasons. Indeed, currently even if I did not click on the disconnect button the session remained open when I close my browser I am still connected to my account.

**Comment by enlivenapp** [comment]
You mean automatically logging out doesn't work?

**Comment by ghost** [comment]
Yes.
Like this :https://stackoverflow.com/questions/20516969/automatic-logout-after-15-minutes-of-inactive-in-php
