### ISSUE TITLE
Add a contact page

### ISSUE THREAD

**Issue by ghost** [enlivenapp/Open-Blog-3#82]
It would be interesting for visitors who are on the blog to contact the site administrator. The page integrate a google map map to locate the address of the admin. The contact page will have a drop-down menu to choose the subject of the message: bug, suggestion, feature request ...
In order to secure the contact form the integration of a recaptcha is essential against malicious people.

**Comment by enlivenapp** [comment]
This is mostly theme/widget based.  I've created a contact form class for a new release.
