### ISSUE TITLE
Redirect according to the language of the visitor

### ISSUE THREAD

**Issue by ghost** [enlivenapp/Open-Blog-3#83]
to redirect a visitor to a different start page depending on the visitors location, for example:

Visitor from the U.S. is directed to domain.com/en
Visitor from Germany is directed to domain.com/de
Visitor from France is directed to domain.com/fr
...

**Comment by enlivenapp** [comment]
That's not how OB deals with language.

It's set in sessions and then there's no need it complicate the URL.
