### ISSUE TITLE
Next version ?

### ISSUE THREAD

**Issue by ghost** [enlivenapp/Open-Blog-3#86]
Question | When will the next version of Open Blog 3 come out and what will be the new features?
We're waiting impatiently.
thank you very much

**Comment by enlivenapp** [comment]
As usual, it'll be ready when it's ready.

Sadly, my father passed and 4 other deaths of folks near me or important to me...  it's been a rough couple of weeks.

You've given me some good ideas as well as mentioned some things I had already planned on doing along with a few other upgrades and even one major change... but that's not official official yet.
