### ISSUE TITLE
Contribuition with new theme and features 

### ISSUE THREAD

**Issue by rrfaria** [enlivenapp/Open-Blog-3#87]
I relly liked the open blog and I would like to contribute with this project creating a theme and  sending suggests to improve more and more

Now I have downloaded the project and I'm trying to understand how it works to create a new theme. 
I'm almost good with this structure and when I finish my test 
I would like to send my contribuition with this.

there are many ideias in my mind to help this project. I really would like to know how can I do that.

**Comment by enlivenapp** [comment]
The basics of creating themes is like that of (CI based) PyroCMS meaning it sits in it's own directory in application/themes/ where all assets, layouts, views, etc are kept.  Feel free to look over application/themes/default/

Notice a few specific needs, {theme_name}.png is named the same as the theme, theme_details.php contains the basic info of the theme notice in that file, `class Theme_{theme-name}`

I have much work to do to make theming more flexible, but feel free to use the default theme as a template.

For coding and additions to the software in general, feel free to send PRs once you've gotten them written and tested.  

Just a little heads up, I have purchased domain names to rebrand Open Blog and I'll be changing the way a few things work and adding features (there's several I'd like to add listed here in the issues pages), themes may be one of those changes, but I'm trying to get the basics done first.
