### ISSUE TITLE
Cant Login after installation

### ISSUE THREAD

**Issue by BrentEerlingen** [enlivenapp/Open-Blog-3#88]
After installing the blog with /installer I tried to login, but I keep getting the error 'Invalid Login'. When I check my database table 'users', there is no user added... 
Anyone knows what I'm doing wrong?

**Comment by enlivenapp** [comment]
Hi Brent,  

Apologies for the late reply.  This is the second time in as many weeks this problem has popped up.

Could you provide your general server details please?

Did `application/config/config.php` and `application/config/database.php` get installed correctly?

If all else is well with the install:

A workaround would be to edit your database replacing(or inserting a new record) the {variables} with your information.  For the salt field you can make up something that’s 22 characters (like RzXJfnEpY5Uq/zDlVHDRxu).  Then go to your site: https://example.com/auth/forgot_password, enter your email and follow the link to reset your password which then should allow you to login successfully after the resulting emails.

If you don’t have email working yet (IE: you’re local and the email function won’t work) Go into your database again and copy the ‘forgotten_password_code’ field text and then to your site again and past it after: http://example.com/reset_password/FORGOTTEN_PASSWORD_CODE
